disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Linux Monk"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

  [params.author]
  name = "Nguyen Minh Phat"
  email = "minhphatnguyen6@gmail.com"
  bio = "The man who fell in love with Linux"

    [[params.author.links]]
    email = "mailto:minhphatnguyen6@gmail.com"

    [[params.author.links]]
    github = "https://github.com/phatnguyen138"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/nguyen-minh-phat"
